spring.application.name=HotelManagementSprintProject

server.port=8087

spring.datasource.url=jdbc:postgresql://172.16.3.53:5432/hotel
spring.datasource.driverClassName=org.postgresql.Driver
<<<<<<< HEAD
spring.datasource.username=priyankaa
spring.datasource.password=1234
=======
spring.datasource.username=postgres
spring.datasource.password=MishtiA@273115
>>>>>>> fd381f44ae36d55c9970e6746dfe08896801ac3c

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true