spring.application.name=HotelManagementSprintProject

server.port=8087

spring.datasource.url=jdbc:postgresql://172.16.3.56:5432/hotel
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=priyankaa
spring.datasource.password=11111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect