spring.application.name=HotelManagementSprintProject

server.port=8087

spring.datasource.url=jdbc:postgresql://172.16.3.53:5432/hotel
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=harshit


spring.datasource.username=shubham
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect